/**
 * Server version reader.
 * Reads the build version from version.json (generated by CI).
 */

import * as fs from 'fs';
import * as path from 'path';

let cachedVersion: string | null = null;

/**
 * Get the server version from version.json.
 * Returns "unknown" if the file doesn't exist (local dev environment).
 */
export function getVersion(): string {
  if (cachedVersion !== null) return cachedVersion;

  const versionFile = path.join(__dirname, '..', 'version.json');
  try {
    const content = fs.readFileSync(versionFile, 'utf-8');
    const data = JSON.parse(content);
    cachedVersion = data.version || 'unknown';
  } catch {
    cachedVersion = 'unknown';
  }

  return cachedVersion!;
}
